apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adm-data
  namespace: gp-engine-malof
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adm-results
  namespace: gp-engine-malof
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
